name: Deploy Server

on:
  push:
    branches:
      - master
    paths:
      - "src/*"
      - ".github/workflows/DeployServer.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test workflow
        run: echo "YAY this workflow is running"
      - name: Add github username
        run: git config --global user.name 'poojaduddalwar'
      - name: Add github email
        run: git config --global user.email 'poojaduddalwar02@gmail.com'
      - name: add heroku remote
        run: git remote add heroku https://heroku:03b4bd45-69cb-4027-bf1d-2e5cf994f6d2@git .heroku.com/pooja-ecommerce-api.git
      - name: Fetch repo
        run: git fetch --unshallow
      - name: push to heroku remote
        run: git push heroku master --force
